#!/bin/sh
BASEDIR=`dirname $0`
exec java \
        -d64 \
        -XstartOnFirstThread \
        -classpath $BASEDIR:$BASEDIR/ServerAccess.jar:$BASEDIR/mindterm.jar:$BASEDIR/swt/swt.jar:$BASEDIR/log4j-1.2.17.jar \
        ru.naumen.servacc.ui.Main
