#!/bin/sh
BASEDIR=`dirname $0`
exec java \
        -d64 \
        -XstartOnFirstThread \
        -classpath $BASEDIR:$BASEDIR/ServerAccess-all.jar:$BASEDIR/swt/swt.jar \
        ru.naumen.servacc.ui.Main
