#!/bin/bash

SWT=/usr/lib/java/swt-gtk-3.7.jar
FLAGS="-Dswt.library.path=/usr/lib/jni -cp distr/servacc.jar:lib/mindterm.jar:$SWT"
ARCH=`uname -i`

if [ "$ARCH" == "x86_64" ] ;then
  FLAGS="-d64 $FLAGS"
fi

java $FLAGS ru.naumen.servacc.ui.Main
