#!/bin/bash
# KISS version control

function usage() {
    echo usage: version new_version_number
}

# move to the project root dir
unset CDPATH
cd "$(dirname "${BASH_SOURCE[0]}")"/..

old_version=$(cat VERSION.TXT)
new_version=$1

if [[ "$old_version" == "" || "$new_version" == "" ]]; then
    usage
    exit 1
fi

# add here files to change
files_to_change=( build.xml VERSION.TXT resource/naumen-server-access.spec )

for a_file in "${files_to_change[@]}"
do
    sed -i "s/$old_version/$new_version/" $a_file
done
